#
# Copyright 2026 The OKDP Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: 2
updates:
  # Update Docker dependencies in spark directory
  - package-ecosystem: "docker"
    directory: "/spark"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(update)"

  # Update Docker dependencies in spark-base directory
  - package-ecosystem: "docker"
    directory: "/spark-base"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(update)"

  # Update Docker dependencies in spark-py directory
  - package-ecosystem: "docker"
    directory: "/spark-py"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(update)"

  # Update Docker dependencies in spark-r directory
  - package-ecosystem: "docker"
    directory: "/spark-r"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(update)"

  # Update GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(update)"